### ISSUE TITLE
RandomForestBase load showing error

### ISSUE THREAD

**Issue by DrigoSalazar** [mljs/random-forest#11]
This is caused in the DecisionTreeClassifier load method not finding the 'name' attribute in the json. The solution is to use the toJSON method of the DecisionTreeClassifier when creating the json in RandomForestBase.toJSON.

I solved it locally so if I get the permissions I would create a PR with this change.

**Comment by stropitek** [comment]
You don't need permission to create a PR :smile: 

Please go ahead and create one.

**Comment by DrigoSalazar** [comment]
I think I need permission to create a branch

**Comment by targos** [comment]
You need to create a fork of the repository (there is a button in the top right of the page). From there you will be able to push a branch and create a pull request.
