### ISSUE TITLE
Can a model be saved?

### ISSUE THREAD

**Issue by paulbrie** [mljs/random-forest#16]
Hi guys! Really cool work!!!

A question: can a model be saved and stored/serialized in a file for later usage?

Thanks,
Paul

**Comment by targos** [comment]
Hello! Yes, a model should be serializable to JSON:

```js
const classifier = new RandomForestClassifier(options);
classifier.train(trainingSet, predictions);
const serialized = JSON.stringify(classifier);

// later, in another process
const classifier = RandomForestClassifier.load(JSON.parse(serialized));
const result = classifier.predict(data);
```

**Comment by creativesites** [comment]
> ```js
> // later, in another process
> const classifier = RandomForestClassifier.load(JSON.parse(serialized));
> const result = classifier.predict(data);
> ```

Awesome work guys. Thank you!
