### ISSUE TITLE
New feature: max_samples option for sample bootstrapping

### ISSUE THREAD

**Issue by nlhlong01** [mljs/random-forest#28]
Hello maintainers,

It would be nice if we have a `max_samples` option to determine the number of samples to draw from the dataset to train each estimator. The RF classifier implementation of Scikit Learn also has [this feature](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html#sklearn.ensemble.RandomForestClassifier).

I have implemented this in my forked version and can quickly create a PR.

**Comment by aiday-mar** [comment]
closed by 219087f

**Comment by aiday-mar** [comment]
closed by 5ca902d074257b82be5947fc56478ab6d369f7b0
