### ISSUE TITLE
Regression example gives weird results since 2.0.0

### ISSUE THREAD

**Issue by sepatin** [mljs/random-forest#32]
Hi 
It seems that results given by regression example are bad since 2.0.0 (same prediction for each element of array).
Predictions seems to be ok with 1.0.3. 

Maybe i missed something ?

Cheers

**Comment by leibatt** [comment]
I observe the same errors, which seem to come from the ml-cart package. The decision tree classifiers return the same (incorrect) result for every prediction. I tested on the [cars](https://github.com/vega/vega-datasets/blob/next/data/cars.json) dataset (predicting cylinders using [weight_in_lbs,horespower] as input) and on a small synthetic dataset. Both the classier and regression models seem to exhibit this error.

**Comment by lpatiny** [comment]
closed by 219087f3a5273d4bf6e8ed89d15d97681826c7fb
